version: '3.7'
services:
  frontend:
    build:
      context: ./frontend-example-docker/
      dockerfile: ./Dockerfile-1-12-fe
    ports:
      - "5000:5000"
  backend:
    build:
      context: ./backend-example-docker/
      dockerfile: ./Dockerfile-1-12-be
    ports:
      - "8000:8000"
