FROM ubuntu:16.04

ARG DEBIAN_FRONTEND=noninteractive

RUN echo DEBIAN_FRONTEND

RUN apt-get update

RUN apt-get install -y rtmpdump ffmpeg python3-dev \
    python3-pip python3-crypto python3-requests python3-lxml

RUN pip3 install --user --upgrade yle-dl

RUN mkdir /usr/downloads

ENTRYPOINT export PATH=$PATH:$HOME/.local/bin && yle-dl -o /usr/downloads/podcast.mp3 https://areena.yle.fi/1-50248693
